FROM nginx
COPY index.html /usr/share/nginx/html
COPY index.css /usr/share/nginx/html
COPY index.js /usr/share/nginx/html
COPY js/ /usr/share/nginx/html/js
ADD default.conf /etc/nginx/conf.d/default.conf
